dataset:
  config: TestImageDatasetConfig
  overrides:
    - name: cache_dir
      value: /home/zadar/.cache/larry/intermediates/image/gen/test_dataset

preprocessor:
  provenanceColumns:
    - key
    - shard_id

pipeline:
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      - name: values
        value:
          - "success"
      - name: op
        value: "nmatches"
      - name: input_column
        value: "status"
      - name: op_config
        value:
          containing: true
          case_sensitive: false
      - name: remove_column
        value: true
      - name: remove_columns
        value:
          - "width"
          - "height"
          - "original_width"
          - "original_height"
          - "error_message"
  - name: NestedExtractionPreprocessor
    config: NestedExtractionPreprocessorConfig
    inputs:
      - name: input_column
        value: "exif"
      - name: output_column
        value:
          - "exif_copyright"
          - "text_original"
      - name: json_path_to_output_column_mappings
        value:
          - jsonPath: "$.'Image Copyright'"
            outputColumn: "exif_copyright"
          - jsonPath: "$.'Image XPComment'"
            outputColumn: "text_original"
      - name: drop_missing_type
        value: any
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      - name: values
        value:
          - "SA"
          - "NC"
          - "ND"
      - name: op
        value: "matches"
      - name: input_column
        value: "exif_copyright"
      - name: op_config
        value:
          containing: true
          case_sensitive: false
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      - name: values
        value:
          - ~
          - ""
      - name: op
        value: "matches"
      - name: input_column
        value: "text_original"
  - name: TextNormalizingMapper
    config: TextMapperConfig
    inputs:
      - name: input_column
        value: "text_original"
  - name: TextTokenizingMapper
    config: SmolLM2TextTokenizingMapperConfig
  - name: URLDownloadingImageMapper
    config: URLDownloadingImageMapperConfig
  - name: ImageResizingMapper
    config: ImageResizingMapperConfig
