preprocessor:
  inputs:
    - name: provenance_columns
      value:
        - librivox_book_id
        - speaker_id

dataset:
  config: LarrySCOTUSManifestDatasetConfig
  overrides:
    - name: cache_dir
      value: /home/zadar/.cache/larry/intermediates/voice/mels/libriheavy/

pipeline:
  - name: ColumnRenamingPreprocessor
    config: ColumnRenamingPreprocessorConfig
    inputs:
      - name: column_name_mappings
        value:
          audio_duration: duration_s
          text_original: text
  - name: ColumnCastingPreprocessor
    config: ColumnCastingPreprocessorConfig
    inputs:
      - name: column_casts
        value:
          audio: "audio_no_decode"
  - name: AudioDurationColumnPruner
    config: AudioDurationColumnPrunerConfig
  - name: AudioQualityPruner
    config: AudioQualityPrunerConfigForTTS
  - name: MelExtractingMapper
    config: MelExtractingMapperConfig
  - name: TextNormalizingMapper
    config: TextMapperConfig
  - name: TextTokenizingMapper
    config: SmolLM2TextTokenizingMapperConfig
