preprocessor:
  inputs:
    provenance_columns:
      - example_id

dataset:
  config: GoogleDOCCIMediaCachedDatasetConfig
  overrides:
    download_extract_cache_dir: /home/zadar/.cache/larry/download_extract/image/google_docci/
    cache_dir: /home/zadar/.cache/larry/intermediates/image/google_docci/
    batch_size: 64

pipeline:
  - name: ColumnRenamingPreprocessor
    config: ColumnRenamingPreprocessorConfig
    inputs:
      column_name_mappings:
        description: text
  - name: TextTokenizingMapper
    config: SmolLM2TextTokenizingMapperConfig
    inputs:
      batch_size: 64
      remove_columns:
        - "split"
        - "image_file"
  - name: ImageResizingMapper
    config: ImageResizingMapperConfig
    inputs:
      batch_size: 64
      filter_null_outputs: true
