preprocessor:
  inputs:
    default_batch_size: 8
    provenance_columns:
      - term
      - docket
    provenance_overrides:
      aligner_model_id: "facebook/wav2vec2-large-960h-lv60-self"

dataset:
  config: LarrySCOTUSUnalignedDatasetConfig
  overrides:
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/unaligned/thelarryproject_scotus-aligned/

pipeline:
  - name: SCOTUSSpeechSegmentationAligningMapper
    config: SCOTUSSpeechSegmentationAligningMapperConfig
    inputs:
      num_proc: 4
      batch_size: 1
      writer_batch_size: 8
      copy_columns:
        - term
        - docket
        - case_name
        - date_argued
        - pdf_url
        - page_url
