preprocessor:
  inputs:
    default_batch_size: 8
    provenance:
      id_columns:
        - term
        - docket
      ancestry:
        models:
          - "facebook/wav2vec2-large-960h-lv60-self"

dataset:
  config: LarrySCOTUSUnalignedDatasetConfig
  overrides:
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/aligned/thelarryproject_scotus-aligned/

pipeline:
  - name: SCOTUSSpeechSegmentationAligningMapper
    config: SCOTUSSpeechSegmentationAligningMapperConfig
    inputs:
      num_proc: 9
      batch_size: 1
      writer_batch_size: 4
      copy_columns:
        - term
        - docket
        - case_name
        - date_argued
        - pdf_url
        - page_url
