preprocessor:
  inputs:
    provenance:
      id_columns:
        - id

dataset:
  config: DatasetConfig
  overrides:
    path: MikhailT/lj-speech
    name: ~
    split: full
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/index/asr/mikhailt_lj-speech-index-asr/

pipeline:
  - name: ColumnCastingPreprocessor
    config: ColumnCastingPreprocessorConfig
    inputs:
      column_casts:
        audio: "audio_no_decode"
        # removes:
        #   - text (normalized lowercase text)
        #   - text_no_preprocessing (original text from gutenberg)
        text: ~
        text_no_preprocessing: ~
  - name: ColumnRenamingPreprocessor
    config: ColumnRenamingPreprocessorConfig
    inputs:
      column_name_mappings:
        duration: duration_s
        # the text_normalized column looks the most like what we want as input to the CTCScoreMapper
        normalized_text: text_original
        file: id
  - name: CTCScoreMapper
    config: CTCScoreMapperConfig
    inputs:
      text_column: text_original
  - name: RowIndexAssigningPreprocessor
    config: RowIndexAssigningPreprocessorConfig
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      op_config:
        min_value: -4
      op: "in_range"
      input_column: "ctc_mismatch"
  - name: AudioDurationColumnPruner
    config: AudioDurationColumnPrunerConfig
  - name: AudioQualityPruner
    config: AudioQualityPrunerConfigForASR
