preprocessor:
  inputs:
    provenance:
      id_columns:
        - id

dataset:
  config: DefaultDatasetConfig
  overrides:
    path: MikhailT/lj-speech
    name: full
    split: ~
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/normalized/asr/mikhailt_lj-speech-normalized-asr/

pipeline:
  - name: ColumnCastingPreprocessor
    config: ColumnCastingPreprocessorConfig
    inputs:
      column_casts:
        audio: "audio_no_decode"
        spoken_text: ~
  - name: ColumnRenamingPreprocessor
    config: ColumnRenamingPreprocessorConfig
    inputs:
      column_name_mappings:
        duration: duration_s
        normalized_text: text_original
        file: id
  - name: AudioDurationColumnPruner
    config: AudioDurationColumnPrunerConfig
  - name: AudioQualityPruner
    config: AudioQualityPrunerConfigForASR
  - name: CTCScoreMapper
    config: CTCScoreMapperConfig
    inputs:
      text_column: text_original
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      op_config:
        min_value: -4
      op: "in_range"
      input_column: "ctc_mismatch"
