training:
  metricsBackend: tensorboard

trainer:
  name: SmokeTestLLMTrainer
  config: SmokeTestLLMTrainerConfig
  overrides:
    - name: num_epochs
      value: 5000
    - name: viz_steps
      value: 500
    - name: dataset_config
      type:
      value:
        path: "parquet"
        data_dir: "/home/zadar/.cache/larry/datasets/text/Trelis_tiny-shakespeare/"
model:
  name: SmokeTestLLM
  config: SmokeTestLLMModelConfig
