preprocessor:
  inputs:
    provenance:
      id_columns:
        - path
        - client_id
        - sentence_id

dataset:
  config: DatasetConfig
  overrides:
    path: parquet
    name: ~
    split: ~
    data_dir: /home/zadar/.cache/larry/datasets/voice/normalized/mozilla-foundation_cv27-normalized/train/
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/index/mozilla-foundation_cv27-index/

pipeline:
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      op_config:
        values:
          - "0"
      op: "matches"
      input_column: "down_votes"
  - name: AudioDurationColumnPruner
    config: AudioDurationColumnPrunerConfig
  - name: AudioQualityPruner
    config: AudioQualityPrunerConfigForTTS
  - name: ColumnValuesPruner
    config: ColumnValuesPrunerConfig
    inputs:
      op_config:
        min_value:
          - -4
      op: "in_range"
      input_column: "ctc_mismatch"
