preprocessor:
  inputs:
    provenance:
      id_columns:
        - librivox_book_id
        - speaker_id

dataset:
  config: DatasetConfig
  overrides:
    path: parquet
    name: ~
    split: ~
    data_dir: /home/zadar/.cache/larry/datasets/voice/normalized/mythicinfinity_libriheavy-large-normalized/train/
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/index/mythicinfinity_libriheavy-large-index/

pipeline:
  - name: ColumnRenamingPreprocessor
    config: ColumnRenamingPreprocessorConfig
    inputs:
      column_name_mappings:
        audio_duration: duration_s
        text_original: text
  - name: ColumnCastingPreprocessor
    config: ColumnCastingPreprocessorConfig
    inputs:
      column_casts:
        audio: "audio_no_decode"
  - name: AudioDurationColumnPruner
    config: AudioDurationColumnPrunerConfig
  - name: AudioQualityPruner
    config: AudioQualityPrunerConfigForTTS
  - name: MelExtractingMapper
    config: MelExtractingMapperConfig
