preprocessor:
  inputs:
    provenance:
      id_columns:
        - librivox_book_id
        - speaker_id

dataset:
  config: MythicInfinityLibriHeavyDatasetConfig
  overrides:
    cache_dir: /home/zadar/.cache/larry/intermediates/voice/normalized/mythicinfinity_libriheavy-large-normalized/

pipeline:
  - name: ColumnRenamingPreprocessor
    config: ColumnRenamingPreprocessorConfig
    inputs:
      column_name_mappings:
        audio_duration: duration_s
        text_transcription: text_normalized
  - name: ColumnCastingPreprocessor
    config: ColumnCastingPreprocessorConfig
    inputs:
      column_casts:
        audio: "audio_no_decode"
  - name: CTCScoreMapper
    config: CTCScoreMapperConfig
    inputs:
      text_column: text_original
